apiVersion: v1
kind: Service
metadata:
  name: swi-ui
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    name: http-port
    targetPort: 80
    protocol: TCP
  selector:
    app: swi-ui
