version: "3"
services:
  ui:
    image: solarwinds/container-ui:latest
    ports:
     - "80:80"
  agent:
    image: solarwinds/container-agent:latest
    privileged: true
    networks:
     - default 
    volumes:
     - /var/run/docker.sock:/host/var/run/docker.sock
     - /proc:/host/proc:ro
